version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
hooks:
  ApplicationStop:
    - location: scripts/applicationStop.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 300
      runas: ubuntu
  ApplilcationStart:
    - location: scripts/applicationStart.sh
      timeout: 300
      runas: ubuntu
